### ISSUE TITLE
Add feature to generate a unit test class or spec when generating a task 

### ISSUE THREAD

**Issue by RoryO** [ConsultingMD/schlepper#3]
When generating a new task, also automatically generate unit test or spec for the task. The generator should inspect `Rails.application.config.generators.test_framework` to determine the host's specified framework.

For `test_unit` or `minitest`, the generated file should look something like

```ruby
#file test/schleppers/#{generated_class_name}_test.rb
require 'test_helper'

class #{generated_test_class_name}Test < ActiveSupport::TestCase
  def test_perform_changes_as_expected
    assert false
  end
end
```

For rspec:

```ruby
# file spec/schleppers/#{generated_class_name}_spec.rb
require 'spec_helper'

describe #{generated_test_class_name} do
  context '#perform' do
    it 'changes as expected' do
      expect(false).to be
    end
  end
end
```

**Comment by kenberland** [comment]
Hello!

**Comment by RoryO** [comment]
I think the version should be bumped to 0.85 or some such. I'm reserving 1.0 when rollback functionality is re-instituted in a scalable fashion.

**Comment by RoryO** [comment]
Finished partially with #4
