### ISSUE TITLE
Turn off output buffering for logs

### ISSUE THREAD

**Issue by 007** [ConsultingMD/schlepper#5]
Output buffering in schlepper makes it scary to run with something like
```
bundle exec rake schlepper:run 2>&1 | tee schlepper-run.log
```
Since buffering is indeterminate (size-based AFAIK?), I get no output for the first N jobs, then a big blast of text once everything's done.  Please disable output buffering (maybe `$stdout.sync = true`?), or explicitly flush after each line / message / job.

**Comment by RoryO** [comment]
Need to also provide some sort of method like `say` from ActiveRecord::Migration, or any `puts` inside of a task, like a progress indicator, will be subject to the same issue

**Comment by RoryO** [comment]
#7
